### PR TITLE
heppy: enable skipevents for preprocessor

### PR DESCRIPTION
**Pull request by jpata**
In order to simply run vhbb_combined.py on the batch system.

### CODE REVIEW

**Comment by jpata** [comment]
Hi, @arizzi, do you suggest something? Can we merge to colin?

**Comment by arizzi** [comment]
I'm not sure I understand the logic... why if we skip on the python loop you want to process all in the preprocessor?

**Comment by jpata** [comment]
I would need it for my local runs, where I want to split the heppy run across one file to multiple jobs. The Heppy preprocessor logic is disabled with that skip. I removed the skip, so that in case the preprocessor does filter (it seems to work correctly), the heppy side simply receives all events from the preproc.

**Comment by arizzi** [comment]
still I do not understand, what you are doing is "if you run with preprocessor then the heppy looper should run on all events"... why?

**Comment by arizzi** [comment]
ah, you rely on the preprocessor having already performed the maxEvent cut?

**Comment by jpata** [comment]
Yes. Sorry for the delay (conference)

**Comment by jpata** [comment]
so do you think it's OK to merge?

**Pull request merged**
