### PR TITLE
merge heppy mem leak fix

### PR DESCRIPTION
**Pull request by jpata**
Merge head from CMG that contains fix to heppy memory leak.
Also ttH fixes for wrapper generation, validation.

### CODE REVIEW

**Comment by bianchini** [comment]
Ciao Joosep, can you have a look why it conflicts?
By the way, this goes into central heppy right?

**Comment by jpata** [comment]
fixed. It came from central heppy/CMG via
`Merge remote-tracking branch 'CERN-PH-CMG/heppy_80X' into vhbbHeppy80X_tth_fixes`
so imho there is no need to factorize. Once we switch to a newer version of heppy it should be there automatically, for the moment we need to merge this one on our code.

**Comment by bianchini** [comment]
Joosep, do we still need it after the latest merge or we can close it?

**Comment by jpata** [comment]
I don't know, haven't had a chance to look at 8_0_11. maybe you can easily see if any of the commits from giovanni are in the PR by Andrea?

**Comment by bianchini** [comment]
does not seem from https://github.com/vhbb/cmssw/pull/460 but please take a look and tell us if we still need to merge or not.

**Comment by jpata** [comment]
we still need it. @arizzi, @bianchini please your opinion: do you want me to cherry pick only Giovanni's commits and make a cbernet/heppy-factorized PR? I rather not waste time making useless PR-s...

**Comment by jpata** [comment]
the other option is to run
`git merge CERN-PH-CMG/heppy_80X` on top of `vhbb/vhbbHeppy80X`

**Comment by bianchini** [comment]
Ciao Joosep. I have seen https://github.com/vhbb/cmssw/pull/464.
Shall we close this one?

**Comment by jpata** [comment]
I would wait for @arizzi or some other person to chime in if it's OK for us to take all developments from CMG, I don't know.

**Comment by arizzi** [comment]
I would wait for their PR on colin branch otherwise it is a nightmare.

**Pull request closed without merging**
