### PR TITLE
New trigger table for 76X MC

### PR DESCRIPTION
**Pull request by silviodonato**
New trigger table for 76X MC. Copied from the triggerTable data.
76X HLT configuration:
http://cmslxr.fnal.gov/source/HLTrigger/Configuration/python/HLT_25ns14e33_v4_cff.py?v=CMSSW_7_6_1

### CODE REVIEW

**Comment by silviodonato** [comment]
I've added a fix about the trigger object input tag: PAT -> RECO

**Comment by degrutto** [comment]
Hi,

I just run vhbb now on a sample of miniAODv2 and I get

Disabling as there is no fallback  ('selectedPatTrigger', '', 'RECO') std::vector<pat::TriggerObjectStandAlone> at first failure
Traceback (most recent call last):
  File "vhbb_combined.py", line 122, in <module>
    p.runcall(looper.loop)
  File "/afs/cern.ch/cms/slc6_amd64_gcc493/external/python/2.7.6-kpegke/lib/python2.7/cProfile.py", line 149, in runcall
    return func(*args, **kw)
  File "/afs/cern.ch/work/d/degrutto/private/vhbbHeppy76X_v0/CMSSW_7_6_3/python/PhysicsTools/HeppyCore/framework/looper.py", line 184, in loop
    self.process( iEv )
  File "/afs/cern.ch/work/d/degrutto/private/vhbbHeppy76X_v0/CMSSW_7_6_3/python/PhysicsTools/HeppyCore/framework/looper.py", line 239, in process
    ret = analyzer.process( self.event )
  File "/afs/cern.ch/work/d/degrutto/private/vhbbHeppy76X_v0/CMSSW_7_6_3/python/PhysicsTools/Heppy/analyzers/core/TriggerObjectsAnalyzer.py", line 53, in process
    allTriggerObjects = self.handles['TriggerObjects'].product()
  File "/afs/cern.ch/work/d/degrutto/private/vhbbHeppy76X_v0/CMSSW_7_6_3/python/PhysicsTools/Heppy/analyzers/core/AutoHandle.py", line 23, in product
    self.ReallyLoad(self.event)
  File "/afs/cern.ch/work/d/degrutto/private/vhbbHeppy76X_v0/CMSSW_7_6_3/python/PhysicsTools/Heppy/analyzers/core/AutoHandle.py", line 52, in ReallyLoad
    raise Exception(errstr)
Exception: 
            Cannot find collection with:
            type = std::vector<pat::TriggerObjectStandAlone>
            label = ('selectedPatTrigger', '', 'RECO')

**Comment by silviodonato** [comment]
Ciao Michele,
which file are you using? Is it 76X?

**Comment by degrutto** [comment]
"root://xrootd.ba.infn.it//store/mc/RunIIFall15MiniAODv2/DYJetsToLL_M-100to200_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/MINIAODSIM/PU25nsData2015v1_76X_mcRun2_asymptotic_v12_ext1-v1/60000/027D7153-29BF-E511-A2BC-0025B3E025B6.root"

**Comment by silviodonato** [comment]
https://github.com/vhbb/cmssw/pull/323

**Comment by degrutto** [comment]
ok thanks, it works now

**Pull request merged**
