### PR TITLE
updated GT with Spring16_25nsV6 JEC

### PR DESCRIPTION
**Pull request by jpata**
https://hypernews.cern.ch/HyperNews/CMS/get/jes/609.html

### CODE REVIEW

**Comment by bianchini** [comment]
Ciao, according to https://twiki.cern.ch/twiki/bin/view/CMS/JetResolution#JER_Scaling_factors_and_Uncertai the JER have been changed as well. They need to go into Heppy: are they already up-to-date there?
@arizzi @jpata

**Comment by jpata** [comment]
do we still do the JER manually by copying the coefficients into the code? I only updated the GT flag and the corresponding JEC files.

**Comment by arizzi** [comment]
mhh I remember of some JER reading code but not sure if it was in Heppy and/or in VhbbHeppy

**Comment by bianchini** [comment]
Ciao, I am afraid it is still like this. One needs to change by hand https://github.com/vhbb/cmssw/blob/vhbbHeppy80X/PhysicsTools/Heppy/python/analyzers/objects/JetAnalyzer.py#L51
Typically these things are already done two-three times by others..
Andrea: do you know if there any update from central Heppy that we may want to take for the next iteration? Maybe the latest JER are already in.

**Comment by arizzi** [comment]
I do not see new stuff here
https://github.com/cbernet/cmssw/pulls?q=is%3Apr+is%3Aclosed
while there is some here
https://github.com/CERN-PH-CMG/cmg-cmssw/pulls?utf8=%E2%9C%93&q=is%3Apr

**Comment by bianchini** [comment]
Ok, several ones from CMG look relevant also to us. How does it work? Do we need to ask Colin to take them?

**Comment by jpata** [comment]
@bianchini https://github.com/vhbb/cmssw/pull/484

**Comment by arizzi** [comment]
@bianchini we can make PR's ourselves if you have a list of the commits we can cherry pick

**Pull request merged**
