### PR TITLE
Add jec

### PR DESCRIPTION
**Pull request by arizzi**

### CODE REVIEW

**Comment by degrutto** [comment]
Hi Andrea,

for 25 ns  we have also  JEC MC based?
https://github.com/CERN-PH-CMG/cmg-cmssw/pull/493

not sure what choice is better for the Spring15 MC at 25 ns...

**Comment by arizzi** [comment]
yep feel free to add the txt files under jec

**Comment by arizzi** [comment]
one thing to notice is that crab config should be updated to be smarter (or dumber?) and to just copy all txt files to the WN rather than selecting by hand which ones are needed

**Comment by arizzi** [comment]
see #148

**Pull request merged**
