### PR TITLE
VtypeSim and genVboson info fix for DY

### PR DESCRIPTION
**Pull request by jstupak**
See #283 

With this PR, when no genVbosons are found we check if the 5th and 6th GenParticles in the event are SF leptons and create a genVboson from their p4 sum.  The leptons are then linked as daughters so the filling of genLep info works as usual.  VtypeSim will then always be set to 0,1, or 5 for MadGraph DY MC.

### CODE REVIEW

**Comment by arizzi** [comment]
5th and 6th seem quite specific... can you perhaps put those in a different branch?

**Comment by jstupak** [comment]
you want just the leptons in a different branch or the genVboson too?  I could trivially drop the leptons completely by not adding them as daughters to the V

**Comment by arizzi** [comment]
I mean the genVboson, I  would like to be a clear "workaround"... i.e. user on the calling side should know they are getting 5+6 and not an actual V at gen level. so call it genVbosonRecovered or something like that

**Comment by jstupak** [comment]
Sure, I will update the PR

**Comment by jstupak** [comment]
Now adding recovered V to genVbosonsRecovered collection.  

NB: VtypeSim will still be -1 in the event no actual genVboson is found but one is recovered, and the daughters will not be added to genLep collection

**Comment by perrozzi** [comment]
(sorry to come late, I would have suggested to create a genLepRecovered flag as well, I don't think there is any reason not to retain the lepton info for these events)

**Comment by arizzi** [comment]
@jstupak  can you make another PR with genLepRecovered?

**Comment by jstupak** [comment]
see #313

**Pull request merged**
