### PR TITLE
Vhbb heppy80 x factorized jec

### PR DESCRIPTION
**Pull request by jpata**
First attempt at #566. I'll take a look at why I have some Lorenzo's commits in here as well later.

### CODE REVIEW

**Comment by jpata** [comment]
Note, needed to revert GT from `Spring16_25nsV6_DATA` while waiting for JERC input.

**Comment by jpata** [comment]
I've checked for closure (seems OK, but not perfect).

See attached:
[jec_factorize.html.zip](https://github.com/vhbb/cmssw/files/604268/jec_factorize.html.zip)

**Comment by jpata** [comment]
@bianchini's commits are included here because PR https://github.com/vhbb/cmssw/pull/556 is not yet merged, I've had to merge it locally for the ttH analysis.
Lorenzo, can you perhaps merge that PR so I can rebase this one cleanly?

**Comment by bianchini** [comment]
Ok, done!

**Comment by arizzi** [comment]
did you also update vhbb.py / vhbbobj.py to store them? (it seems not to me but I may have missed it)

**Comment by jpata** [comment]
@arizzi the JECs are stored in `autophobj.py` directly in heppy, but possibly we want to put it in a different place in case the list of factorizations is configured at runtime.

**Comment by arizzi** [comment]
does it mean that automatically every Heppy use will get them? We should make this not default-on because many heppy user do not care (and it increase sizebly the ntuple size I imagine)

**Comment by arizzi** [comment]
thanks. We should also create a PR against central colin branch (that is probably ahead of us)

**Comment by jpata** [comment]
Superceded by https://github.com/vhbb/cmssw/pull/570 and https://github.com/cbernet/cmssw/pull/78

**Pull request closed without merging**
