### PR TITLE
Vhbb heppy80 x kin fit

### PR DESCRIPTION
**Pull request by bianchini**
This PR introduces a KinFit for the Zll channel (Vtype=0,1) based on T. Bluntschli (ETHZ) original code.

### CODE REVIEW

**Comment by arizzi** [comment]
can you clean the conflicts?
Have you considered 
PhysicsTools/KinFitter
that we use in other channels?
(@cvernier can you show HH->4b implementation?)

**Comment by cvernier** [comment]
@bianchini @arizzi the HH->4b implementation is done on top of the vheppy ntuples here importing the library built in PhysicsTools/KinFitter

**Comment by arizzi** [comment]
@bianchini can you fix the conflicts?

**Comment by arizzi** [comment]
I fixed the conflicts, I'll test for speed and then merge

**Pull request merged**
