### PR TITLE
New regression with target  genPt/pt (with genPt>0) 

### PR DESCRIPTION
**Pull request by degrutto**
train with target GenPt/Pt and let genPt>0 (previously >20). This shows the regression is more flat vs pt. Along the change, we remove the chMult in training (shown to be not modelled in data) and fix a bug in application of the systematics for jet_corr variables

### CODE REVIEW

**Comment by arizzi** [comment]
can you add a description please? and a meaningful titile

**Comment by silviodonato** [comment]
Ciao Michele,
I suggested to replace the neHEF and chHEF with neHEF+chHEF (you are simply removing chHEF).
These are the distribution of:
- chHEF (very bad): [2]
- neHEF (bad): [3]
- neHEF+chHEF (almost ok): [4]

I see a bad MC/data discrepancy also in rho [1].

[2]: http://sdonato.web.cern.ch/sdonato/VHbb/ZvvHbb/V20/Plots3Mar/old2/Stacks_expertAllnominal_v0.0.0_CRnewCRQCD/CR_TTbarTight_Jet_chHEF0_%5B_ZH___WH___ggZH_%5D.png

[3]: http://sdonato.web.cern.ch/sdonato/VHbb/ZvvHbb/V20/Plots3Mar/old2/Stacks_expertAllnominal_v0.0.0_CRnewCRQCD/testBTagX_Jet_neHEF0_%5B_ZH___WH___ggZH_%5D.png

[4]: http://sdonato.web.cern.ch/sdonato/VHbb/ZvvHbb/V20/Plots3Mar/old2/Stacks_expertAllnominal_v0.0.0_CRnewCRQCD/CR_TTbarTight_Jet_HEF0_%5B_ZH___WH___ggZH_%5D.png

[1]: http://sdonato.web.cern.ch/sdonato/VHbb/ZvvHbb/V20/Plots3Mar/old2/Stacks_expertAllnominal_v0.0.0_CRnewCRQCD/testBTagX_rho_%5B_ZH___WH___ggZH_%5D.png

**Comment by degrutto** [comment]
Hi @arizzi  I added a comment

@silviodonato ok, but these requires a new training...  bad this was nou pointed oulast wed meeting or I did not get from you these suggestions before...

**Comment by degrutto** [comment]
@silviodonato  the problem I do not know what to replace with rho... or how much we need it, I guess we do, to get a proxy to the L1Offet correction

**Comment by silviodonato** [comment]
I've asked to use neHEF+chHEF in cms-heppy-hbb mailing list on Feb 22nd [1].
About the rho, can we use nPVs?

[1]: https://groups.cern.ch/group/cms-heppy-hbb/Lists/Archive/Flat.aspx?RootFolder=%2Fgroup%2Fcms-heppy-hbb%2FLists%2FArchive%2Ffeedback%20on%20V20&FolderCTID=0x012002006DA8F28E61FE3E468E4B255DB4850EB3

**Comment by arizzi** [comment]
@degrutto I guess a retrain along what silvio proposes is worth being done.
Concerning rho,  you can check if the other rhos we are now saving are better reproduced...

**Comment by silviodonato** [comment]
You can check all the regression-related variables (for ZvvHbb) in http://sdonato.web.cern.ch/sdonato/VHbb/ZvvHbb/V20/Plots3Mar/RegressionPlots/

Unfortunately the rhoN and rhoCHPU are -1 (even in TV21 ntuples)!

**Comment by degrutto** [comment]
@arizzi sure I can do a new training.
@silviodonato  can you try rho / NPVs and see if it is ok i ttbar and jet_corr / rho ?

**Comment by degrutto** [comment]
Hi, so I moved to train rho and neHEF to be nPVs and totHEF 
the performance on singla are really the same

**Pull request merged**
