### PR TITLE
Updated Hbb tagging variables

### PR DESCRIPTION
**Pull request by gkasieczka**

### CODE REVIEW

**Comment by arizzi** [comment]
did you test the speed of this?

**Comment by arizzi** [comment]
it seems to be 3 times slower than it was.... I'd say we need to store the c++ computed variables in some taginfo like structure and just dump that into the ntuple on the heppy side... I told Dinko/Caterina that the TagInfo was more important than the discriminator from day zero... 

In addition you need to add a check against division by zero such as
-     tau2_vertexEnergyRatio = tau2_vertexSum.E() / allSum.E()
+     tau2_vertexEnergyRatio = tau2_vertexSum.E() / allSum.E() if allSum.E() > 0 else 0.


this is too slow to be taken as it is right now

**Comment by gkasieczka** [comment]
Also adding @cvernier 

Yes - Dumping the variables in C and just retrieving them is also my preferred option. 

However, until we can do that, what do you think about a pragmatic solution? Ie only calculating these variables for a fraction of events. My understanding is that the main purpose to have them included is validation This could also be performed on a smaller sample if it does not bias.


Cheers,
Gregor

**Comment by arizzi** [comment]
if we could define a region of phase space for validation we can implement
a preselection in the code and run it only there.

**Comment by arizzi** [comment]
anyhow V20 is running without it since yesterday. We can add it for V21
(exp in 2 weeks)

**Comment by gkasieczka** [comment]
Either a region of phase-space or a coinflip (1/3?).

**Comment by arizzi** [comment]
Hi,
I'd rather define a control region that we like (for example  a boosted
ttbar enriched one?)

ciao
andrea

**Comment by arizzi** [comment]
any update here?

**Comment by arizzi** [comment]
ping?

**Comment by gkasieczka** [comment]
Ciao Andrea,

sorry - Caterina and I discussed this a while back.

My proposal would be (following your idea):
HTT candidate > 200 GeV with a decent mass window + fRec + 1 electron or
muon

What do you think? I'm happy to add the cuts if you agree.

Cheers,
Gregor

**Comment by arizzi** [comment]
given that we use it also in HH=> 4b I'll put in OR a criterium such as (2
fatjet with pt > 200 and HT > 600)
@cvernieri what do you think?

**Comment by cvernier** [comment]
ok, pt > 250 GeV should enough.

**Comment by arizzi** [comment]
ok I will test the speed and merge

**Comment by arizzi** [comment]
this is not mergeable after I merged the other.. can you rebase on current HEAD?

**Comment by arizzi** [comment]
apologies hold on before rebasing because things have been messed up

**Comment by arizzi** [comment]
fixed the HEAD, you can rebase on that

**Comment by gkasieczka** [comment]
So when I cms-merge-topic git now checks out a bunch of CMSSW modules. Did
we change the base version? (Tested on a clean 7_6_3 install)

Cheers,
Gregor

**Comment by degrutto** [comment]
Hi gregor, try 763patch2

**Comment by arizzi** [comment]
any update here? we need to launch V21 asap

**Comment by gkasieczka** [comment]
Please see:
https://github.com/vhbb/cmssw/pull/417

The rebase introduced a few issues but now it works again.

Cheers,
G

**Comment by arizzi** [comment]
so this one can be closed?

**Comment by gkasieczka** [comment]
Yes

**Pull request closed without merging**
