### PR TITLE
SF's for ele/mu

### PR DESCRIPTION
**Pull request by bianchini**
I have added json files with ele/mu SF under data/, and a python class to read them under python/.
I have also added the standlone class for btag reweighting

### CODE REVIEW

**Comment by arizzi** [comment]
are those run by default anywere? if not why not?

**Comment by bianchini** [comment]
Ciao Andrea, "run" you mean from inside heppy/vhbb?
I was thinking that  it is not worth it having the SF saved in the ntuples, because there is amlost no chance of having the latest SF's in time before submission of vhbb. Actually I would remove also all the bTagWeights, which we won't certainyl have in time, and keep all SF as standalone macros. What you think?

**Comment by perrozzi** [comment]
(for the record, I agree with Lorenzo's proposal to keep them as standalone, at least for the next iterations)

**Comment by arizzi** [comment]
well, for sure for next iteration we need to keep them standalone too, but
I'd like anyhow to have the infrastructure to compute and store them ready

**Comment by bianchini** [comment]
Ok, let me work out something. It should be straightforward. I would add them in the vhbb trees, but keep them commented.

**Comment by bianchini** [comment]
Ok, done with this new PR:
https://github.com/vhbb/cmssw/pull/304

**Pull request merged**
