### PR TITLE
CMG, heppy: 8_0_11 updates, memory leak fix

### PR DESCRIPTION
**Pull request by jpata**
IMHO it makes no sense to cherry pick as proposed in https://github.com/vhbb/cmssw/pull/456, so here I merged everything from 8_0_11 again in order to be able to run on the grid without the memory leak on GenParticles.

### CODE REVIEW

**Comment by arizzi** [comment]
so this is merged, not cherry-picked right? now if no cherry-picking / rebasing is needed to merge CMG on cbernet we are good... otherwise is going to be a merge nightmare anyhow

**Comment by jpata** [comment]
Yes, this is a pure `git merge remotes/CERN-PH-CMG/heppy_80X`.
Indeed, I can try if merging CMG on cbernet works cleanly, in this case it should be clean to merge later in no matter what order. Or maybe someone can suggest CMG to open a nice PR against coling?

**Comment by arizzi** [comment]
just asked it to @gpetruc

**Comment by arizzi** [comment]
see:
https://github.com/cbernet/cmssw/pull/77

**Comment by jpata** [comment]
OK, nice. so what do you want to do? I guess they won't merge cbernet#77 that one until a few days...

**Comment by arizzi** [comment]
I suggest we merge directly 77 into our repo

**Comment by arizzi** [comment]
@jpata colin just merged

**Comment by jpata** [comment]
I've seen it. do you want me to make a PR against vhbb from colin?

**Comment by arizzi** [comment]
that would be great

**Pull request closed without merging**
