### PR TITLE
Updated double electron trigger names

### PR DESCRIPTION
**Pull request by dcurry09**

### CODE REVIEW

**Comment by bianchini** [comment]
This branch name looks suspicious: dcurry09:CMSSW_8_1_X
You should be using 805.
Please close this PR and make a new one using the correct release.

**Comment by degrutto** [comment]
Hi David,

maybe you started from a wrong CMSSW?
try to start from 8_0_5 and do not use vX (X=1,2,3) in the trigger names, but rather v*

**Comment by dcurry09** [comment]
Hi,

In this case the double electron trigger names have not changed(module vX)
and PR #448 can be ignored.

Also, Ive made sure I am on 8_0_X for all future PRs.

cheers,

On Thu, Jun 9, 2016 at 11:39 AM, michele de gruttola <
notifications@github.com> wrote:

> Hi David,
> 
> maybe you started from a wrong CMSSW?
> try to start from 8_0_5 and do not use vX (X=1,2,3) in the trigger names,
> but rather v*
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/vhbb/cmssw/pull/448#issuecomment-224847184, or mute
> the thread
> https://github.com/notifications/unsubscribe/AEJ5mjxAb145mHlXjHVV9_6MXCiE5SCFks5qJ99sgaJpZM4IxyWw
> .

## 

## David Curry

Physics Department
CERN B8 R-031 || University of Florida, NPB 1218
curry@phys.ufl.edu
076 291 0492

**Comment by degrutto** [comment]
ok, so I will delete the PR, thanks

**Comment by degrutto** [comment]
ok, I will than close the PR, thanks

**Pull request closed without merging**
