### PR TITLE
Regression spring15

### PR DESCRIPTION
**Pull request by cvernier**
weights for (VH and VBF) regression using spring15 samples

### CODE REVIEW

**Comment by arizzi** [comment]
what is the VBF regression? is it used anywhere?

**Comment by arizzi** [comment]
and how do we handle Vtype=4 ? they could be used by VBF too... isn't it?

**Comment by azzurrip** [comment]
Yes we need a Jet_pt_regVBF leaf

**Comment by cvernier** [comment]
Shall we clone JetRegression.py to add the jet_pt_regVBF or do you suggest something else?

**Comment by arizzi** [comment]
no, we better split evaluation and attribute setting!! 
Simple rule of thumb: each time you can and paste 30 lines and keep them identical, that was not the right way of implementing it.

**Comment by arizzi** [comment]
something like
evaluateRegression(...current args..., attrName="pt_reg") : 
   ...existing code...
   setattr(jet,"attrName",value)  
  instead of  jet.pt_reg=value


then you call it "normally" for VH and you call it
evaluateRegression(....,"pt_regVBF") 
for VBF

**Comment by arizzi** [comment]
did you at least try running it?! it fails with python errors in a few places!

**Pull request merged**
