### PR TITLE
Vhbb taus 2015 apr01

### PR DESCRIPTION
**Pull request by veelken**
superseedes https://github.com/vhbb/cmssw/pull/41#issuecomment-88500677

### CODE REVIEW

**Comment by arizzi** [comment]
still cannot merge... can you rebase or try figuring what is the conflict?

**Comment by veelken** [comment]
This pull request has all the tau specific configuration parameter changes done in vhbb rather than general heppy.

I have run git fetch, but the pull request does still not merge automatically. Sorry.

**Comment by arizzi** [comment]
take a fresh CMSSW_7_2_2_patch2 area and do
git cms-merge-topic vhbb:vhbbHeppy722patch2
git fetch my-cmssw vhbbTaus_2015Apr01:vhbbTaus_2015Apr01
git merge vhbbTaus_2015Apr01

and see what goes wrong

**Comment by veelken** [comment]
Ok, thanks for the instructions.

I have created a new PR https://github.com/vhbb/cmssw/pull/44 .

**Pull request closed without merging**
