### PR TITLE
Heppy 7 6 3 patch2

### PR DESCRIPTION
**Pull request by arizzi**
merge with V21 from colin
includes egamma stuff of  #400 (to be checked)
@bianchini

### CODE REVIEW

**Comment by bianchini** [comment]
Ok thanks! I will check it.
In case, it should be just about enabling the flag "smearElectrons".

**Comment by arizzi** [comment]
@bianchini can you please make a PR enabling the flag and test that it behaves as #400 ? (and if so close that one)

**Comment by bianchini** [comment]
Yes, checking now on 300 Zll events..

**Comment by bianchini** [comment]
No, it crashes miserably...@emanueledimarco: do you have by chance an example configuration for https://github.com/vhbb/cmssw/blob/vhbbHeppy76X/PhysicsTools/Heppy/python/analyzers/objects/LeptonAnalyzer.py#L53 ?

**Comment by bianchini** [comment]
@matteosan1 @emanueledimarco 
Ok, I worked out this:
LepAna.doElectronScaleCorrections = {
        'data' : 'EgammaAnalysis/ElectronTools/data/76X_16DecRereco_2015',
        'GBRForest' : [os.environ['CMSSW_BASE']+'/src/EgammaAnalysis/ElectronTools/test/GBRForest_data_25ns.root','gedelectron_p4combination_25ns'],
        'isSync' : False
        }
where I got the GBRForest file by running
cmsRun getGBRForest_cfg.py
Can you confirm that it is fine?
I see that if I enable it the electron.pt values are slightly different from the ones in the miniAOD.

**Comment by emanueledimarco** [comment]
@bianchini @arizzi @matteosan1 

it is correct. You can pick up the root file already committed in CMGTools:
'$CMSSW_BASE/src/CMGTools/RootTools/data/egamma_epComb_GBRForest_76X.root',

which is committed in cmgtools-lite repository:
  https://github.com/emanueledimarco/cmgtools-lite/tree/76X/RootTools/data

**Pull request merged**
