### PR TITLE
Color flow

### PR DESCRIPTION
**Pull request by bortigno**
Adding pull angle vector coordinates in the phi/eta plane (phi and magnitude) for jetsForHiggs

### CODE REVIEW

**Comment by arizzi** [comment]
Did you test the speed? is it ok to have it on python or should we rather wrap it in C++

**Comment by bortigno** [comment]
Ciao Andrea, I did not test the speed. How do i add my function to the time analyser? I am agnostic on python/C++.

**Comment by bortigno** [comment]
Hi Andrea, I saw the time report. I think it is very nice. unfortunately my functions are missing. I was trying to understand why but a quick investigation wasn't successful.

**Comment by arizzi** [comment]
please send me the logs

**Comment by arizzi** [comment]
any update? do you have a c++ implementation?

**Comment by arizzi** [comment]
move to V14 waiting for C++ implemenation

**Comment by arizzi** [comment]
news?

**Comment by bortigno** [comment]
I started working on it today. For my knowledge I was trying to understand the reason why a c++ wrapper should make it faster. I am not really sure I understand it. Could you help me with that? Anyhow reviewing it the code I already reduce the timing by a factor 2 just removing useless stuff in the python code. Tomorrow I will go through it again and let you know. Thank you.

**Comment by bortigno** [comment]
Sorry, stupid question, forget about it. I'll let you know tomorrow about the wrapper.

**Comment by bortigno** [comment]
Hello. Question: which kind of c++ objects are the jetsForHiggs? are these vector<pat::Jet>? Thank you

**Comment by bortigno** [comment]
Hello, color flow c++ wrapper is done now. Can you please review it? I will be probably add some features (for instance difference clustering methods) to it but this is the baseline. Thank you.

**Comment by arizzi** [comment]
@bortigno for the records, the keyword "Heppy:" in the comments should be used only for commits affecting PhysicsTools/Heppy (i.e. the common part of Heppy) not for commits affecting VHbbAnalysis/Heppy !

**Pull request merged**
