### PR TITLE
Vhbb heppy722patch2 taustuff

### PR DESCRIPTION
**Pull request by arizzi**
replaces #13 and #15 
@veelken

### CODE REVIEW

**Comment by veelken** [comment]
Hi Andrea,

thank you very much for merging the pull requests.

I see only 1 sample that we need for the tth study:
	/TTbarH_HToTauTau_M-125_13TeV_amcatnlo-pythia8-tauola/Phys14DR-AVE30BX50_tsg_PHYS14_ST_V1-v1/MINIAODSIM

I am looking at the VHbb Ntuples now and I notice that TBrowser->Inspect does not tell me the type of the branches.
Could you tell me how you read e.g.
	Jet_pt
?

Thank you,


Christian

**Comment by arizzi** [comment]
Try tree->sprint()
Il 01/mar/2015 14:08 "Christian Veelken" <notifications@github.com> ha
scritto:

**Comment by arizzi** [comment]
I meant print ... Not sprint
Il 01/mar/2015 14:09 "Andrea Rizzi" <andrea.rizzi@cern.ch> ha scritto:

**Comment by veelken** [comment]
Ok, I did tree->Print() and I see now that the branches are stored as Double_t or Int_t [*].

The number of entries in the branch matches the number of processed events (98 in my case), however, so I think I am still missing something.

Do you store the information for jets as Double_t[nJet] or std::vector<Double_t> in order to handle more than one jet per event ?

I noticed that the list of triggers defined in VHbbAnalysis/Heppy/test/vhbb.py does not contain the lepton+tau and double-tau triggers that we need for the tth analysis yet. I am wondering if I can just add these triggers to the TrigAna.triggerBits config with new keys (e.g. "EleTau") or do the keys need to match a certain naming scheme ?

I noticed also that the matching of offline reconstructed leptons (e, mu, tau) to the HLT trigger objects is not present in the Ntuple yet. Can you remind me how you do the trigger matching (or does this still need to be implemented ?)

[*]

*............................................................................*
*Br  457 :Jet_mass  :                                                        *
*         | Double_t mass for Cental+fwd jets after full selection and cleaning, sorted by b-tag*
*Entries :       98 : Total  Size=       7555 bytes  File Size  =       4050 *
*Baskets :        1 : Basket Size=      32000 bytes  Compression=   1.71     *
*............................................................................*

**Comment by arizzi** [comment]
Hi,
yes the information is store as Jet_pt[nJet], Jet_eta[nJet] etc..

yes you can add your triggers there.

Concerning the trigger matching we should check if something already exists
from the CMG side but for sure we (VH) did not implement it.


PS: I'm surprised we are storing as Double rather than Float... a bug
perhaps... let me see

**Comment by arizzi** [comment]
please make a PR adding the dataset in datasets.txt and the trigger bits in vhbb.py

**Comment by veelken** [comment]
Ok, the changes are included in PR #19

**Pull request merged**
