### PR TITLE
From cmssw 7 6 3

### PR DESCRIPTION
**Pull request by veelken**
This adds the lepton MVA from CMG.

### CODE REVIEW

**Comment by bianchini** [comment]
Ciao Cristian, will you implement also the POG MVA id for electrons?

**Comment by veelken** [comment]
Hi Lorenzo,

I understood from Joosep that he is already working on it.
I will contact Joosep on skype and check how far he got. I had a quick look at the EGamma electron ID MVA and it seems non-trivial for me to port this to CMSSW 7_6_x in heppy,
so better not to duplicate the effort.

Cheers,


Christian

**Comment by jpata** [comment]
@bianchini we just discussed with @veelken, I will do it still today after all the other things as I can remind myself how I did it for 74 and the recipe should be the same for 76. If it's not straightforward then we re-discuss.

**Comment by jpata** [comment]
from the twiki:
"At present the electron MVA IDs are fully integrated in the official CMSSW releases: 7.4.16 and later for the 74X series, and 7.6.3 and later for the 76X series."
so this merge is not even needed, as I expected.

**Comment by veelken** [comment]
Requires PR #286
( https://github.com/vhbb/cmssw/pull/286 )

**Pull request merged**
