### PR TITLE
add first batch of mc and data for 80X

### PR DESCRIPTION
**Pull request by perrozzi**

### CODE REVIEW

**Comment by jpata** [comment]
Ciao, these are miniAODv2 samples, I just tried to run our vhbb_combined.py code on some of these samples and got some MINIAOD errors:

```
= CMSSW:     treeNumpy.vfill(name, [ v(collection[i]) for i in xrange(num) ])
== CMSSW:   File "/tmp/26897001.grid-ce.physik.rwth-aachen.de/glide_OhhIDg/execute/dir_26980/CMSSW_8_0_5/python/PhysicsTools/Heppy/analyzers/core/autovars.py", line 23, in __call__
== CMSSW:     ret = self.function(object)
== CMSSW:   File "/tmp/26897001.grid-ce.physik.rwth-aachen.de/glide_OhhIDg/execute/dir_26980/CMSSW_8_0_5/python/VHbbAnalysis/Heppy/vhbbobj.py", line 307, in <lambda>
== CMSSW:     NTupleVariable("mtrimmed",   lambda x : x.userFloat("ak8PFJetsCHSTrimmedMass"),   help="Trimmed Mass"),
== CMSSW: Exception: none of the 2 overloaded methods succeeded. Full details:
== CMSSW:   float pat::PATObject<reco::Jet>::userFloat(const string& key) =>
== CMSSW:     An exception of category 'UnknownUserFloat' occurred.
== CMSSW: Exception Message:
== CMSSW: Requested UserFloat ak8PFJetsCHSTrimmedMass is not available! Possible UserFloats are:
```

The sample file in vhbb.py is miniAODv1, there it works.

**Comment by jpata** [comment]
Apparently the trimmed and filtered masses got removed in v2, @gkazieczka is removing them also from vhbbobj.py in an upcoming PR.

**Comment by perrozzi** [comment]
ok, miniAODv2 is the way to go as we would not have all the samples in v1

**Comment by bianchini** [comment]
@arizzi @degrutto @perrozzi @jpata 
Ciao, what is the status here? Do we have a decently complete set of samples?
Thanks!

**Comment by perrozzi** [comment]
list updated, cfr https://github.com/vhbb/cmssw/pull/435/commits/50b572cb961abd1355e7703575f02cc7aeced602

**Comment by bianchini** [comment]
Ciao, Luca, I can't see any VH signal samples... are they still missing?

**Comment by perrozzi** [comment]
signals have been injected last because of the missing trigger in MC and the need to create a new RAWOADSIM dataformat...

**Pull request merged**
