### PR TITLE
Vhbb heppy76 x gen stuff

### PR DESCRIPTION
**Pull request by bianchini**
fixed what I think was a bug (division by zero very rarely):
https://cmsweb.cern.ch/scheddmon/096/cms1756/160206_121331:arizzi_crab_VHBB_F20_02_ggZH_HToBB_ZToLL_M125_13TeV_powheg_Py8__fall15MAv2-pu25ns15v1_76r2as_v12-v1/job_out.1.2.txt

### CODE REVIEW

**Comment by arizzi** [comment]
check if #357 is ok too (that's what I used in H20)

**Comment by bianchini** [comment]
Ciao, yes it's ok. To be super safe, I would also change if pt_corr<0.: into if pt_corr<=0.:
https://github.com/arizzi/cmssw/commit/44e6b28cbd777366789e465218eba5823a207f7e#diff-43a52f0c8516b4c611119f1ae0df2c84R66
because there is a division by pt_corr later in the code. Otheriwse it's ok.

**Comment by arizzi** [comment]
can I close?

**Comment by bianchini** [comment]
Yes!

**Pull request closed without merging**
