### PR TITLE
Clean iso leptons pt>100 from ak08 jets 

### PR DESCRIPTION
**Pull request by degrutto**
Currently we do not clean AK08 from isolated high pt leptons (as for example we do for AK04 jets),
so that for example for boosted WH or ttbar we end up counting as an AK08 also the isolated leptons

for example running on 10K ttbar events
you can see
tree->Scan("vLeptons_pt[0]:vLeptons_eta[0]:vLeptons_phi[0]:FatjetAK08ungroomed_pt[0]:FatjetAK08ungroomed_eta[0]:FatjetAK08ungroomed_phi[0]:FatjetAK08ungroomed_pt[1]:FatjetAK08ungroomed_eta[1]:FatjetAK08ungroomed_phi[1]", "(Vtype==2 || Vtype==3)  && vLeptons_pt[0]>200")
************************************************************************************************************************
*    Row   * vLeptons_ * vLeptons_ * vLeptons_ * FatjetAK0 * FatjetAK0 * FatjetAK0 * FatjetAK0 * FatjetAK0 * FatjetAK0 *
************************************************************************************************************************
*      486 * 227.97969 * 1.6994822 * 2.4628152 * 414.51736 * -0.371218 * -0.268958 * 264.51855 * 1.7090501 * 2.4791479 *
*      941 * 216.82115 * -0.250433 * -2.473064 * 417.10134 * -0.492968 * -2.398186 * 401.56655 * -1.319406 * 0.9346565 *
*     2219 * 220.49176 * -0.345123 * 1.5495907 * 244.27256 * -0.356651 * 1.5516041 * 242.80322 * 1.7964932 * -2.217689 *
*     2612 * 240.26806 * -1.280980 * 2.6154904 * 416.45639 * -1.387354 * 2.8326878 * 267.41754 * -1.198281 * -0.268394 *
*     2995 * 268.97140 * -0.729955 * 0.2212234 * 378.55676 * -0.309298 * 3.0287020 * 329.17950 * -0.759287 * 0.2278359 *
*     3110 * 344.84329 * -0.791675 * -0.934284 * 609.24823 * 0.2727501 * 2.2796807 * 492.21444 * -0.784295 * -1.046502 *
*     5585 * 221.64776 * -1.223543 * -0.439981 * 392.36306 * -1.094269 * 1.7670828 * 337.48385 * -0.468150 * -2.750352 *
*     6054 * 239.62789 * -2.004043 * 0.3158723 * 289.74194 * -2.056790 * 0.2839619 * 172.13600 * -1.835923 * -2.495727 *
*     6448 * 237.61502 * 0.1964717 * -2.256531 * 248.66830 * 0.2003203 * -2.254620 * 236.59410 * 0.8230695 * 1.0604845 *
*     6916 * 256.59451 * -0.583562 * -2.046752 * 468.81778 * -0.964035 * 0.9934120 * 276.19131 * -0.588372 * -2.051098 *
*     6953 * 207.53952 * -0.693762 * -0.673449 * 230.25509 * -0.731006 * -0.675769 *           *           *           *
*     7232 * 213.28254 * -1.685189 * -0.266786 * 271.40948 * 0.6291755 * 2.6919140 * 243.38847 * -1.677636 * -0.280771 *
*     7326 * 202.98083 * -1.417835 * 1.7001608 * 224.86529 * -1.419605 * 1.6977075 * 200.12959 * -1.390052 * -1.588781 *
*     7526 * 249.98646 * -0.899727 * 0.6889757 * 331.88818 * -0.946527 * 0.7356168 * 271.72921 * 1.9366679 * -1.607415 *
*     8529 * 320.48111 * -0.355744 * 1.9079818 * 400.94149 * -0.368724 * 1.8704458 * 241.24726 * -0.394449 * -1.252551 *
*     8826 * 288.50488 * 1.6246022 * -0.331949 * 352.05279 * 1.2703681 * 2.8939623 * 321.78347 * 1.6189461 * -0.327402 *
*     8890 * 201.60336 * 1.1921196 * -0.826848 * 251.10688 * -0.228606 * 2.3004219 * 232.50924 * 1.2182252 * -0.825409 *
*     9038 * 241.99644 * 0.5485758 * -3.038404 * 393.31189 * 0.8125209 * 0.1394629 * 264.90271 * 0.5466814 * -3.024556 *
*     9503 * 227.15168 * -0.276045 * -1.893557 * 255.80079 * -0.292449 * -1.918410 * 171.60766 * -1.531095 * 1.5476977 *
**********************************************************************************************************************

while after this cleaning 

tree->Scan("vLeptons_pt[0]:vLeptons_eta[0]:vLeptons_phi[0]:FatjetAK08ungroomed_pt[0]:FatjetAK08ungroomed_eta[0]:FatjetAK08ungroomed_phi[0]:FatjetAK08ungroomed_pt[1]:FatjetAK08ungroomed_eta[1]:FatjetAK08ungroomed_phi[1]", "(Vtype==2 || Vtype==3)  && vLeptons_pt[0]>200")
************************************************************************************************************************
*    Row   * vLeptons_ * vLeptons_ * vLeptons_ * FatjetAK0 * FatjetAK0 * FatjetAK0 * FatjetAK0 * FatjetAK0 * FatjetAK0 *
************************************************************************************************************************
*      486 * 227.97969 * 1.6994822 * 2.4628152 * 414.51736 * -0.371218 * -0.268958 *           *           *           *
*      941 * 216.82115 * -0.250433 * -2.473064 * 401.56655 * -1.319406 * 0.9346565 *           *           *           *
*     2219 * 220.49176 * -0.345123 * 1.5495907 * 242.80322 * 1.7964932 * -2.217689 * 230.71885 * -1.296662 * -0.602271 *
*     2612 * 240.26806 * -1.280980 * 2.6154904 * 267.41754 * -1.198281 * -0.268394 *           *           *           *
*     2995 * 268.97140 * -0.729955 * 0.2212234 * 378.55676 * -0.309298 * 3.0287020 *           *           *           *
*     3110 * 344.84329 * -0.791675 * -0.934284 * 609.24823 * 0.2727501 * 2.2796807 *           *           *           *
*     5585 * 221.64776 * -1.223543 * -0.439981 * 337.48385 * -0.468150 * -2.750352 *           *           *           *
*     6054 * 239.62789 * -2.004043 * 0.3158723 * 172.13600 * -1.835923 * -2.495727 *           *           *           *
*     6448 * 237.61502 * 0.1964717 * -2.256531 * 236.59410 * 0.8230695 * 1.0604845 *           *           *           *
*     6916 * 256.59451 * -0.583562 * -2.046752 * 468.81778 * -0.964035 * 0.9934120 *           *           *           *
*     6953 * 207.53952 * -0.693762 * -0.673449 * *           *           *           *           *           *
*     7232 * 213.28254 * -1.685189 * -0.266786 * 271.40948 * 0.6291755 * 2.6919140 *           *           *           *
*     7326 * 202.98083 * -1.417835 * 1.7001608 * 200.12959 * -1.390052 * -1.588781 *           *           *           *
*     7526 * 249.98646 * -0.899727 * 0.6889757 * 271.72921 * 1.9366679 * -1.607415 * 224.64009 * -0.484142 * -2.671160 *
*     8529 * 320.48111 * -0.355744 * 1.9079818 * 241.24726 * -0.394449 * -1.252551 *           *           *           *
*     8826 * 288.50488 * 1.6246022 * -0.331949 * 352.05279 * 1.2703681 * 2.8939623 *           *           *           *
*     8890 * 201.60336 * 1.1921196 * -0.826848 * 251.10688 * -0.228606 * 2.3004219 *           *           *           *
*     9038 * 241.99644 * 0.5485758 * -3.038404 * 393.31189 * 0.8125209 * 0.1394629 *           *           *           *
*     9503 * 227.15168 * -0.276045 * -1.893557 * *           *           *           *           *           *
************************************************************************************************************************ 

@gkasieczka @cvernier   @arizzi @jpata 
hope you like the code,
please also suggest other checks we could do,
or for example if we want at all to clean, and also to clean CA15

### CODE REVIEW

**Comment by cvernier** [comment]
@degrutto how much is changing the efficiency for H-signal? probably we should try to compare efficiency for an HH>4b sample.

**Comment by arizzi** [comment]
need experts answer before merging....

**Comment by arizzi** [comment]
plus it doesn't merge anymore

**Comment by cvernier** [comment]
I'd like to see the efficiency for H-signal, in an another sample : HH>4b and see that the signal efficiency there is unchanged. Also lower pt threshold should be tested too.

**Comment by arizzi** [comment]
@cvernier can't you check how many selected leptons we have in our signal events? aren't we removing those events anyhow to reduce ttbar?

**Comment by cvernier** [comment]
Indeed for fully hadronic final state it should be the same. I just want to check that the signal efficiency is unchanged as expected.

**Comment by cvernier** [comment]
I check it's fully efficient for HH>4b.

**Pull request merged**
