### PR TITLE
Add trkMET_phi vhbb heppy74 x mdg

### PR DESCRIPTION
**Pull request by degrutto**
needed for QCD rejection

### CODE REVIEW

**Comment by degrutto** [comment]
MET type1 in vhbb is currently missing the residual corrections (due to an old globaltag in the miniaod), which would be cured with a preprocessor module. We may want to ignore this but we should know we may experience some discrepancy in data/MC until a new rereco (of MC and data).
We have now the full information for trkMET (pt and phi) which can be used together with mht(jet30) as a valid temporary solution. For the trigger weights in ZnnHbb we should parametrize vs metraw_pt!

**Comment by arizzi** [comment]
this cannot be merged anymore (btw can you avoid changing the filename and nevents in these PRs?)

**Comment by degrutto** [comment]
ok, 
should i start from the current vhbb.py  ?

**Comment by arizzi** [comment]
yes, I merged what I could

**Comment by degrutto** [comment]
ok, please have a look at 
https://github.com/vhbb/cmssw/pull/165

**Comment by arizzi** [comment]
PS: you can push on the same branch without opening a new PR ;-)

**Comment by degrutto** [comment]
ok !

**Pull request closed without merging**
