### PR TITLE
Add spring16 el mva

### PR DESCRIPTION
**Pull request by capalmer85**
@arizzi This doesn't work quite yet.

### CODE REVIEW

**Comment by arizzi** [comment]
any news here? still need help?

**Comment by capalmer85** [comment]
I looked a little deeper yesterday and they are using a different module
now for the mva reader.  This PR must be redone.  I'm planning on giving it
a try this afternoon.

FYI, some files will eventually appear in CMSSW 80X, but I will have to add
them in the mean time.

**Comment by arizzi** [comment]
you can merge their PR (in our git) that adds the file if one exists
already!

**Comment by capalmer85** [comment]
ah ok.  I'll do that then.

**Comment by capalmer85** [comment]
#640 supersedes

**Pull request closed without merging**
