### PR TITLE
Dev extra softdrop plus nsub

### PR DESCRIPTION
**Pull request by gkasieczka**
Added Softdrop z=0.2, beta=1 for CA/R=1.5 together with N-Subjettiness calculated from these jets.

### CODE REVIEW

**Comment by arizzi** [comment]
is this for V12?

**Comment by gkasieczka** [comment]
It's a relatively small/independent change that adds a useful variable we
found recently. It would be nice to have it in V12 if still possible.

**Comment by arizzi** [comment]
did you check the speed?

**Comment by gkasieczka** [comment]
Not explicitly - but we already have a few groomed masses in and
n-subjettiness post-grooming should be faster than before (which is also
already in)

**Pull request merged**
