### PR TITLE
Fix l2 l3

### PR DESCRIPTION
**Pull request by cvernier**

### CODE REVIEW

**Comment by arizzi** [comment]
mhh this was already fixed... how come it wasn't ported to 80X? (my fault anyhow...)

**Comment by bianchini** [comment]
Ops, I did not see it was against vhbb76X... shall I revert it?

**Comment by arizzi** [comment]
ahh.. this was against 76X... then I'm not sure what you did because it was already fixed by another commit I think... can you anyhow check if the fix is correctly in 80X?

**Comment by bianchini** [comment]
No, the fix is not there in 80X..

**Comment by arizzi** [comment]
then it is my fault and I never pushed back the fix

**Comment by bianchini** [comment]
Ok, no problem. Since it's just a couple of lines I can add them myself in a next PR

**Comment by bianchini** [comment]
@cvernier 
I tried to add the lines of these PR but I get a crash:
  File "vhbb_combined.py", line 133, in <module>
    p.runcall(looper.loop)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/python/2.7.11-ikhhed/lib/python2.7/cProfile.py", line 149, in runcall
    return func(_args, *_kw)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_0_11/python/PhysicsTools/HeppyCore/framework/looper.py", line 184, in loop
    self.process( iEv )
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_0_11/python/PhysicsTools/HeppyCore/framework/looper.py", line 239, in process
    ret = analyzer.process( self.event )
  File "/mnt/t3nfs01/data01/shome/bianchi/VHbb_80X/CMSSW_8_0_11/python/VHbbAnalysis/Heppy/AdditionalBoost.py", line 1044, in process
    jet.JEC_L2L3Unc = jet.jetEnergyCorrUncertainty
  File "/mnt/t3nfs01/data01/shome/bianchi/VHbb_80X/CMSSW_8_0_11/python/PhysicsTools/Heppy/physicsobjects/PhysicsObject.py", line 28, in **getattr**
    return getattr(self.physObj, name)
AttributeError: 'pat::Jet' object has no attribute 'jetEnergyCorrUncertainty'

**Pull request merged**
