### PR TITLE
tth 743 updates (heppy)

### PR DESCRIPTION
**Pull request by jpata**
This is the heppy side of #67. Jet corrections/uncertainties up for discussion.

### CODE REVIEW

**Comment by arizzi** [comment]
@gpetruc @cbernet please have a look and comment before we make a PR against colin branch

**Comment by cbernet** [comment]
Hi Andrea, HeppyCore untouched so fine with me. I trust you guys for the jet physics.

**Comment by arizzi** [comment]
@gpetruc does it look ok to you? if so @jpata can you make a PR against and starting from latest branch of colin, aka cbernet:heppy_7_4_4_patch4 ?

**Comment by cbernet** [comment]
@jpata the new branch is now heppy_7_4_5.

**Comment by jpata** [comment]
talk about hitting a moving target... what is the recommended way to port a PR from an older to a newer release?
I would extract a big patch with git diff and apply it on the new release with git apply - will that be OK? everything will be in one commit.

**Comment by arizzi** [comment]
I guess git rebase is better

**Comment by cbernet** [comment]
Hi Joosep, 

You could simply create a new branch in 745 (the one you will PR), then merge my heppy branch, and then merge your old branch into it. 

Colin.

**Comment by jpata** [comment]
@arizzi OK. can you give me an short example how to do rebase it in CMSSW? I only did it so far for projects which didn't use sparse checkout and sometimes it was still a bit of a mess...

@cbernet won't I get a ton of conflicts/changes from the differences between the releases?

sorry sparse checkout is a bit new to me..

**Comment by arizzi** [comment]
I'm not an expert on rebase I just do git rebase --onto A  B...C and follow examples I find online

**Comment by jpata** [comment]
ok if you say it works I will try. thanks.

**Comment by jpata** [comment]
ported to 745 in cbernet/cmssw#41. As discussed with @arizzi, I will add the per-jet b-tag weights from PhysicsTools/Heppy/python/physicsutils/BTagWeightCalculator.py.

**Comment by jpata** [comment]
Free to close.

**Comment by arizzi** [comment]
new branch is vhbbHeppy74X see #75

**Pull request closed without merging**
