### PR TITLE
Cleaner implementation to run on data

### PR DESCRIPTION
**Pull request by arizzi**
Configuration for running on data should now be much cleaner.
Beside the sample isData/isMC switch the only other thing to do at config level is that metFilter FLAGS should go on RECO rather than PAT process name.

In order to avoid config duplication now the vhbb.py or vhbb_combined.py are just imported and the data config is way simpler.

the vhbb_combined_data is not yet working because the preprocessor is not DATA vs MC aware  (@gkasieczka can you have a look?)

@degrutto

### CODE REVIEW

**Comment by arizzi** [comment]
@jpata I think more than substructures it is about in general the preprocessor stuff, can you have a look if   @gkasieczka is not around?

**Comment by jpata** [comment]
OK, I can do basic validations on the substructure stuff in data today. The real expert (G.K.) will return on Monday.

**Comment by arizzi** [comment]
no rush, we can wait monday too..

**Comment by gkasieczka** [comment]
#160 should make the preprocessor data/MC aware. It's based on this PR.

**Comment by arizzi** [comment]
can you make also a PR containing only the Heppy change to @cbernet repository?

**Pull request merged**
