### PR TITLE
Vhbb heppy74 x jetmetvalidation

### PR DESCRIPTION
**Pull request by bianchini**
A new macro to validate jets and MET

### CODE REVIEW

**Comment by degrutto** [comment]
Hi Lorenzo, are you done with it? I;d say so, just to confirm so that I'll proceed to merge, thanks

**Comment by bianchini** [comment]
I am done, you can merge.
Lorenzo
Il giorno 23/ott/2015 18:43, "michele de gruttola" <notifications@github.com>
ha scritto:

**Comment by bianchini** [comment]
Ah Michele: keep in mind that one commit changes a file in Heppy..

**Comment by degrutto** [comment]
can you change that particular commit to start with "Heppy: ...." ? that way Andrea will collect them all and pull vs Colin repo

**Comment by bianchini** [comment]
Ciao Michele,
It should be already flagged with Heppy:
Lorenzo
Il giorno 23/ott/2015 22:04, "michele de gruttola" <notifications@github.com>
ha scritto:

**Comment by degrutto** [comment]
perfect

**Pull request merged**
