### PR TITLE
added new flags

### PR DESCRIPTION
**Pull request by bianchini**
Added new flags https://github.com/vhbb/cmssw/issues/361

### CODE REVIEW

**Comment by bianchini** [comment]
Ciao, I have added the latest 76X SF as announced in https://hypernews.cern.ch/HyperNews/CMS/get/physics-announcements/3778.html, and restructured a bit the code. I have also added to the tree 3 more branches for the cMVAv2 SF.

**Comment by bianchini** [comment]
@perrozzi @arizzi @degrutto @azzurrip
Ciao, in 6eb117c I have added a new TH1 counter to be filled with genWeight*puWeight so we can normalise the BGenFilter samples.

**Comment by perrozzi** [comment]
+1 for me

**Comment by azzurrip** [comment]
Hi, not sure it is good to entangle genWeight and puWeight,
maybe better to save their sums separately, if both are needed ?

In any case they must be uncorrelated,
and puWeight should usually preserve the normalisation.


On 17 Feb 2016, at 15:01, bianchini <notifications@github.com<mailto:notifications@github.com>> wrote:


@perrozzi<https://github.com/perrozzi> @arizzi<https://github.com/arizzi> @degrutto<https://github.com/degrutto> @azzurrip<https://github.com/azzurrip>
Ciao, in 6eb117c<https://github.com/vhbb/cmssw/commit/6eb117c37b7d4a01185fa33b55bdb5277cf25990> I have added a new TH1 counter to be filled with genWeight*puWeight so we can normalise the BGenFilter samples.

**Comment by bianchini** [comment]
Ciao, I have added the latest csvv2 reweighting and cleaned a bit the data/csv dir from old files

**Comment by arizzi** [comment]
the correct MET filter flags should be later propagated to central HEPPY

**Pull request merged**
