### PR TITLE
Heppy gennufromtop

### PR DESCRIPTION
**Pull request by jpata**
Uses the modified[1] GeneratorAnalyzer to save generated neutrinos form top quarks.

[1] https://github.com/cbernet/cmssw/pull/26

### CODE REVIEW

**Comment by arizzi** [comment]
I'd rather make a PR from colin's HEAD so that we do not conflict later... I'll make it and close this one (is it the exact same as cbernet#26?)

**Comment by jpata** [comment]
It is not the same. cbernet#26 modifies GeneratorAnalyzer in HeppyCore, this one modifies vhbb.py. The commits do not conflict. Please advise what is the suggested way to do such dual PR-s in the future.
Thanks.

**Comment by arizzi** [comment]
I merged both (#24 first) and it worked.
In general I'd keep completely factorized any PR for PhysicsTools/Heppy ... if you make them to colin repo directly, then it would be better to wait for his merge and then merge colin's head to our repo

**Comment by jpata** [comment]
I see, thanks. I had the impression that having modified separate files from separate commits, they should be independent, but indeed cbernet#26 needs to be merged first to make vhbb.py work python wise (not git-wise). Would you prefer if I made the HeppyCore PR-s in the future directly against vhbb as well, but basing from cbernet/heppy_7_2_2_patch2?

**Comment by arizzi** [comment]
that would be ok too.
anyhow I try to keep the changes in PT/Heppy (btw HeppyCore is yet another package.. mind the naming) to a minimum and send them back in bulk. 

anyhow what else are we missing to push the V10 button?

**Pull request merged**
