### PR TITLE
Dev ak8calib

### PR DESCRIPTION
**Pull request by gkasieczka**
Added full four vectors for AK08 pruned - calibrated as well as uncalibrated.

See also: https://github.com/vhbb/cmssw/issues/185

@degrutto @cvernier

### CODE REVIEW

**Comment by gkasieczka** [comment]
Also added HTT candidate and subjet calibrations

**Comment by degrutto** [comment]
Hi Gregor,
thanks for doing this,

I just tried it and I believe it makes the jobs,
https://degrutto.web.cern.ch/degrutto/2015/Hbb/boostedZH/HmassAK08pruned.png

red is AK08pruned mass and blue is the "cal" mass (ZnnHbb sample, with met>300)

**Comment by degrutto** [comment]
Hi @gkasieczka ,

I also noticed by chance today looking at the ntuplas, that we do not clean the AK08 jets and the leptons... Just to keep in mind

   Michele

**Comment by degrutto** [comment]
Hi @gkasieczka 
Do you have time to rebase it for 76X?
In particular I am not sure we do need anymore to recluster the AK08 jets.
Also the bbTagger should be taken from the miniAOD now, correct?
For the inputs variables, my understanding is also they have changed wrt the one we save in this PR for 74X... 

Sorry to point to many issues at the same time

let me know,
cheers

  Michele

**Comment by arizzi** [comment]
@cvernier @ferencek you guys have PR ready too?

**Comment by gkasieczka** [comment]
Hi Michele,

@cvernier and I have been working on these issues.

The PR250 is ported to 76X and some additional information is added, see:
https://github.com/cvernier/cmssw/commits/adding-more-ak08

We are already taking ak08 from the MiniAOD, but some additional groomed variables are calculated from reclustering.

The bb-Tager is freshly calculated - if Caterina/Dinko agree we can also take it from the file.

It will not be possible to calculate all Hbb tagger input variables in the python version (as we discussed some time ago). Porting of the others is also going on in the branch I linked above.

Depending on how pressed for time we are we could also couple out the additional bb-input vars and start by sending the PR for the jet correction issues immediately. What do you think?

Cheers,
Gregor

**Comment by arizzi** [comment]
I think if you have something ready we can include.
it is ok to have multiple PRs

**Comment by degrutto** [comment]
Hi, 
yes I agree with Andrea

but if the bbTag is the same as in the  miniAOD I would take that ones
(but Dinko and Caterina knows better than me for sure)

it is useful to add also  the energy fractions to the AK08 jets?

thanks a lot for the fast reply

**Comment by ferencek** [comment]
I haven't done any Heppy developments so no PRs from my side. Concerning the bbTag, if possible, I would recommend keeping the one stored in MiniAOD (the one derived from MiniAOD will generally be very similar but not exactly the same as the one stored in MiniAOD).

Also, take note of https://github.com/cms-sw/cmssw/pull/12890 and https://github.com/cms-sw/cmssw/pull/12988 that will allow re-deriving the bbTag without reclustering ak8 jets.

**Comment by arizzi** [comment]
should we just close this or you want to import it in 74X branch anyhow?

**Comment by arizzi** [comment]
I'll close, it can be reopened if someone need for 74X

**Pull request closed without merging**
