### PR TITLE
ttH variables, wrapper generation (core PhysicsTools/Heppy)

### PR DESCRIPTION
**Pull request by jpata**
Factorized PR #8 - PhyscisTools Heppy. Added PDF variables to PDF analyzer, leptonic tops to generator, LHE Nb/Nc/Nl/Ng, python/cpp wrapper gen.

### CODE REVIEW

**Comment by arizzi** [comment]
I'll test it and merge later today.. thanks for factorizing and implementing the suggestions!

**Comment by arizzi** [comment]
even better would be if you can rebase this PR on cbernet:heppy_7_2_2_patch2 (i.e. pure Heppy with no VHbb stuff) so that we can merge it there directly

**Comment by arizzi** [comment]
I rebased myself

**Comment by jpata** [comment]
OK - I was nearly done with the rebase myself...

**Pull request closed without merging**
