### PR TITLE
Vhbb heppy76 x new b tag

### PR DESCRIPTION
**Pull request by bianchini**
Added new POG SF in btagSF.py (but keep "old" in vhbbobj.py)

### CODE REVIEW

**Comment by bianchini** [comment]
Ciao, I have added the latest SF from the POG. They are "preliminary", so they may change and I have not changed what we have in vhbbobj.py (they still point to 74X SF). I would recommend people to use btagSF.py standalone for the moment.

**Comment by arizzi** [comment]
why should we keep the old in vhbbobj.py??

**Comment by bianchini** [comment]
They me outdated soon... When do you want to submit the big 76X production? I am not sure when the blessed SF will come

**Comment by arizzi** [comment]
well better outdated than 74X (just wrong, meant for another release...)

**Comment by bianchini** [comment]
Done

**Pull request merged**
