### PR TITLE
Heppy: update QGL training (Spring15dr)

### PR DESCRIPTION
**Pull request by tomcornelis**
Most up to date QGL training, from Spring15dr samples

### CODE REVIEW

**Comment by arizzi** [comment]
can you please make a PR against cbernet repositories
@cbernet @gpetruc

**Comment by cbernet** [comment]
Not sure how these developments play with https://github.com/CERN-PH-CMG/cmg-cmssw/pull/498. If they go together,  Tom should PR to CMG as well, or  both Tom and Francesco should PR to me: 
https://github.com/cbernet/cmssw/tree/heppy_7_4_7

**Comment by arizzi** [comment]
in fact I'd say the best is to both make PR against @cbernet repo

**Comment by cbernet** [comment]
Fine with me. 
So Francesco, please close https://github.com/CERN-PH-CMG/cmg-cmssw/pull/498, and Tom please close this one. 
Then, you can both PR to https://github.com/cbernet/cmssw/tree/heppy_7_4_7

**Pull request closed without merging**
