### PR TITLE
enable lumi-based processing in crab

### PR DESCRIPTION
**Pull request by jpata**
can run LumiBased in crab.

### CODE REVIEW

**Comment by arizzi** [comment]
how does the main heppy loop knows about the lumiMask with this?

**Comment by jpata** [comment]
sorry, I miss the point. if the preprocessor removes the event, the main loop will never see it, so you only need to filter it once...

**Comment by arizzi** [comment]
well, we do not always run with preprocessor... it is not nice to include a
feature the works only if preprocessor is on... at least to central Heppy

**Comment by jpata** [comment]
OK, I see. Would you be fine with this for vhbb only? There are no real modification to central heppy here, anyway we don't care about crab in central heppy.

**Comment by arizzi** [comment]
yes we can use it for vhbb

**Pull request merged**
