### PR TITLE
fix filenames

### PR DESCRIPTION
**Pull request by arizzi**

### CODE REVIEW

**Comment by arizzi** [comment]
@degrutto

**Comment by degrutto** [comment]
@arizzi thanks it looks good, and sorry for having created mess .... I definitely do not know how to merge conflicts of PRs

**Comment by degrutto** [comment]
adding @chernyavskaya just to make 100% sure we are including the latest files for VBFblikelihood

**Comment by chernyavskaya** [comment]
Hi, 

We need to delete the ine with old weight  from heppy_crab_config 

../TMVA_blikelihood_vbf_cmssw76.weights.xml',  


And leave only this one with new weights 
      "../TMVA_blikelihood_vbf_cmssw76_h21trained.weights.xml",

The new weights xml file was added to "test" directory , one directory up. Is it alright ?

**Comment by arizzi** [comment]
having one file more does no harm, having one less does. just be sure that you always update both crab/ and crab_data for files that are not symlinked

**Comment by chernyavskaya** [comment]
Ok, sorry again. I make sure next time. 

Do I have to make another PR adding the weights file to crab data or you will change it this time together with the rest of the changes ?

**Comment by arizzi** [comment]
it is already in this PR!

**Pull request merged**
