### PR TITLE
Sync to @cbernet heppy_8_0_19

### PR DESCRIPTION
**Pull request by jpata**
I needed to solve a few conflicts between `vhbb/vhbbHeppy80X` and `cbernet/heppy_8_0_19` in order to test #570 and related PR-s.

In particular, the `outservicename` has changed, as well as `type` -> `the_type` in the `AutoFillTreeProducer`.

I made this PR for reference (NOT to be merged) so that you can see what changes I needed to do.

### CODE REVIEW

**Comment by arizzi** [comment]
I added @gkasieczka and @jpata in  the "coreteam" so that you guys
should be able to merge PRs and admin this repo.

I suggest we branch new stuff for V25 perhaps changing a bit our methods, i.e.:

- put full base release version number in the branch name (8_0_19)
- we can start syncing the stuff you need in a 8_0_19 branch and then
go ahead with more features for V25

@jpata do you want to start the above?

**Comment by jpata** [comment]
@arizzi do you mean making a new `heppy_8_0_19_vhbbHeppy80X` branch here in this repo that syncs `vhbbHeppy80X` to `cbernet/heppy_8_0_19` without any additions, and then our new features on top of that branch?

**Comment by arizzi** [comment]
right

**Comment by jpata** [comment]
Superceded by https://github.com/vhbb/cmssw/pull/572

**Pull request closed without merging**
