### PR TITLE
Vhbbheppy74 x add scale variations

### PR DESCRIPTION
**Pull request by bianchini**
Add just first 9 weights for scale variations. 
(skip for the moment the other hundreds of weights for PDF reweighting...)

### CODE REVIEW

**Comment by perrozzi** [comment]
ciao lorenzo, do you think ut would be worth adding also the pdf weights (in case are not there already)?

**Comment by bianchini** [comment]
Ciao Luca, I was considering adding them as well... the problem is that there many of them, as far as I could see there are the eigenvectors of NNPDF and at least a full CTEQ set. I was afraid about adding too many floats if we are not sure about their use. @arizzi: what you think? Shall we add the full LHE_weights?

**Comment by arizzi** [comment]
sizes?

**Comment by bianchini** [comment]
- QCD scales variations: all combinations of mu_R x2 - x0.5 and muF x2 - x0.5, except mu_R x2, mu_F x0.5 and mu_R x0.5, mu_F x2 (see CitationsForGenerators)
    - Members of NNPDF3.0LO or NLO (default PDF, central + 100 variations, alpha_s = 0.130). Numbers are different if the sample uses the 4-flavor version of PDFs.
   - NNPDF3.0 with alpha_s varied to 0.118
   - NNPDF3.0 with alpha_s varied to 0.119
    - CTEQ6L1 or CT10 (alternative PDF)
    - Members of MMHT14lo68cl or nlo or nnlo (alternative PDF, central + 50 variations)
    - Members of HERAPDF15 (alternative PDF, central + 20 variations) 

If we want everything looks like 500 * sizeof(float).
I can give you a better estimate in a few min.

**Comment by bianchini** [comment]
@arizzi: I have updated the jet pf ID cuts according to https://twiki.cern.ch/twiki/bin/view/CMS/JetID#Recommendations_for_13_TeV_data. There is ~no change for eta<3.0, but for eta>3.0 the new cuts are much looser because the old nhf<0.99 cut was killing quite a lot of jets. This i a heppy commit.

**Comment by arizzi** [comment]
that's way too much (and likely we do not need it)
let's precompute the weights corresponding to variations we care for
systematics

**Comment by perrozzi** [comment]
thanks a lot. I would say that at least NNPDF30 replicas (100) and the 2 alpha_s variations are needed (one could argue if they are needed now, but better to have them ready to be stored I would say)

**Comment by bianchini** [comment]
@perrozzi @arizzi: ciao, I have changed a bit the code, now we can specify which weights we want to save in VHbbAnalysis/Heppy/python/VHGeneratorAnalyzer.py by using the weight id. For now I restricted to the scale variations. 
To get the map between a systematic and an id one has to dump LHERunInfo like in https://twiki.cern.ch/twiki/bin/viewauth/CMS/LHEReaderCMSSW. I have no clue of how to access Runs from heppy, so we have to rely on someone making the systematic-to-id table before running (I don't know for example which id corresponds to the alpha_s shifted pdfs).

**Comment by perrozzi** [comment]
ciao lorenzo, thanks a lot. I am asking myself if it would make sense not to dump all the lhe weights in a single leaf and to separate them (scale_LHEweights, NNPDF30_LHEweights, ... or so) for clarity in the mapping at analysis level

**Comment by perrozzi** [comment]
For the record, I dumped the header of 3 example LHE files from 3 different samples among those we use, one for each generator (madgraph, amc@nlo, powheg). I attach below the files.
Things are A BIT COMPLICATED...

powheg and madgraph have 1001-1009 (scale variations)

powheg has: 2001-2100 (NNPDF30_nlo_as_0118) + 2101-2102 (alpha_s variations NNPDF30_nlo_as_0117,NNPDF30_nlo_as_0119) + 3001-3053 (CT10nlo) + 3054-3055 (CT10nlo_as_0117,CT10nlo_as_0119) + 4001-4051 (MMHT2014nlo68clas118) + 4052-4056 (alpha_s variations MMHT2014nlo_asmzsmallrange)

amc@nlo has: 2001-2100 (NNPDF30_nlo_nf_5_pdfas) + 2101-2102 (alpha_s variations, need to search for the range)

madgraph has: 1-9 (scale variations) + 10-110 (NNPDF30_lo_as_0130) + 111-211 (NNPDF30_lo_as_0130_nf_4) + 212 (NNPDF30_lo_as_0118) + 213-313 (NNPDF23_lo_as_0130_qed) +314 (NNPDF23_lo_as_0119_qed) + 315 (cteq6l1) + 316-366 (MMHT2014lo68cl) + 367-369 (MMHT2014lo_asmzsmallrange) + 370-390 (HERAPDF15LO_EIG) + 391 (NNPDF30_nlo_as_0118) + 392 (NNPDF30_nlo_as_0119) + 393-445 (CT10nlo) + 446 (MMHT2014nlo68cl)

so at least for the scale variations, we need to include 1-9 to catch the LO

for PDF, I think that 2001-2100 + 2101-2102 are good for NLO and 10-110 + ? (no consistent alpha_s variations) for LO

finally, soon a tool will be available to transform on the fly the nnpdf replicas into hessian eigenvectors (easier to deal in combine)

further details in this recent talk by Josh
https://indico.cern.ch/event/459797/contribution/2/attachments/1181555/1710844/mcaod-Nov4-2015.pdf

[DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt](https://github.com/vhbb/cmssw/files/37267/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt)
[ZH_HToBB_ZToLL_M120_13TeV_powheg_pythia8.txt](https://github.com/vhbb/cmssw/files/37234/ZH_HToBB_ZToLL_M120_13TeV_powheg_pythia8.txt)
[ttHJetTobb_M120_13TeV_amcatnloFXFX_madspin_pythia8.txt](https://github.com/vhbb/cmssw/files/37233/ttHJetTobb_M120_13TeV_amcatnloFXFX_madspin_pythia8.txt)

**Comment by arizzi** [comment]
for scale variation I'd just save the 4 variations for muR and muF (0.5,2 x
2)
for PDF I think I'm a bit lost in the jungle... but I'm pretty sure that
long list is overkill, can you propose a subset and collapse that to just a
few nuisances?

**Comment by bianchini** [comment]
@arizzi Ciao, ok I see from the slides that the scale variations can fit into three nuisances (one up/down at the time (2*2) + both up/down at the same time (2)).
@perrozzi: Luca, do you know if Josh tool for replicas to Hessian conversion is already available?
Another pb is that the id's are process dependent. Do we need to put some logic like if(MG5): take id in [bla bla] else bla bla ?

**Comment by bianchini** [comment]
@arizzi @perrozzi 
Ciao, with this commit we now save a leaf called LHE_weights_scale and one LHE_weights_pdf.
The latter is empty for now, the former contains just the minimal set of weights (six), already nornalised correctly (LHE_weights[XXX]/LHE_originalWeight). To make our lives easier, they are ordered such that:
LHE_weights_scale[0] <=> muR Up
LHE_weights_scale[1] <=> muR Down
LHE_weights_scale[2] <=> muF Up
LHE_weights_scale[3] <=> muF Down
LHE_weights_scale[4] <=> muR/muF Up
LHE_weights_scale[5] <=> muR/muF Down
I tested on a powheg and amC samples are are ok. MG5 seems also ok, but please double check!

**Comment by arizzi** [comment]
why should we store/use both up and not one up and one down?

**Comment by perrozzi** [comment]
I would say simply because that is what is recommended by the theorists

**Comment by perrozzi** [comment]
(ps for me the PR can be merged, we can postpone the PDF to a subsequent PR)

**Pull request closed without merging**
