### PR TITLE
updated list of available datasets

### PR DESCRIPTION
**Pull request by perrozzi**

### CODE REVIEW

**Comment by degrutto** [comment]
Hi Andrea, Luca,
 shall we add also a list for data ? Not sure on how many dataset we should run to cover all analysis

**Comment by arizzi** [comment]
just those with B!=0 please

**Comment by degrutto** [comment]
the selection is done via the json, as far as I can tell the datasets are divided not according the magnet status

**Comment by arizzi** [comment]
we need to commit the jsons too then

**Comment by degrutto** [comment]
yes absolutely

**Comment by degrutto** [comment]
I will take care right now, but the json will change of course with the time

**Comment by perrozzi** [comment]
we discussed this already but you didn't like it, anyway an option is not to filter via json while making the ntuples. we can develop a quick macro, to be run afterwards making use of the json itself, to produce a filtered version of the trees

**Comment by degrutto** [comment]
Hi Luca, so you would prefer to run with the json dcsonly and then select yourself the events with a script?  I'm not 100% sure myself it is the best option, but we can discuss

**Comment by degrutto** [comment]
ok @perrozzi I did what you suggested, let's discuss https://github.com/vhbb/cmssw/pull/166

**Comment by arizzi** [comment]
in any case the lumi/pu weight should be in sync with the json so it makes little sense to use json only.
In Run1 we used json only for running the step1 (now replaced by miniaod) and use actual json for step2.
especially given the Bon Boff, dcsonly could be not enough and the lumi profile quite different given the LHC is ramping up.

**Pull request merged**
