### PR TITLE
Add jetsd r08 to higgs candidate

### PR DESCRIPTION
**Pull request by degrutto**
Old doHiggs3cj moved to doHiggsAddJetsdR08.
Paolo checked it reproduced exactly what has been proposed by him,
i.e. one adds to the bestCSV pair any jets (pt>15, |eta|<3.0, puId and jetId) with dR<0.8 by any of the two jets.

I hope the python code is acceptable, I believe we should be fine for what regards the time, because I limit the loop to the jest which satisfy the requirements above,

cheers

 Michele

### CODE REVIEW

**Comment by degrutto** [comment]
V13 or V12?

**Comment by arizzi** [comment]
V12... we still have plenty of issues to solve

**Comment by arizzi** [comment]
@degrutto can you please fix, after merging other PR's this one cannot be merged anymore, there must be some conflicts likely in vhbb.py
Please also have a look at space vs tabs from your editor, it seem we have some indent nightmare in a few places

**Comment by degrutto** [comment]
Hi Andrea, ok can you just tell me when I can start with the vhbbHeppy74X and I'll resubmit

**Comment by arizzi** [comment]
for today I stopped working on it, so you can go ahead... (PS: how about the list of changes for data?)

**Comment by degrutto** [comment]
please see the #116

**Pull request closed without merging**
