### PR TITLE
complete list of Spring15 signal samples for X>4b search

### PR DESCRIPTION
**Pull request by cvernier**

### CODE REVIEW

**Comment by arizzi** [comment]
@perrozzi how this integrates with your script?
Il 07/lug/2015 05:33, "Caterina Vernieri" <notifications@github.com> ha
scritto:

**Comment by perrozzi** [comment]
currently these samples are fitered. 
It is sufficient to remove the words 'Grav' and 'Radion' from the list
https://github.com/vhbb/cmssw/blob/vhbbHeppy74X/VHbbAnalysis/Heppy/test/crab/diff_datasets.py#L5
to have them shown. Shall I include them in the file
https://github.com/vhbb/cmssw/blob/vhbbHeppy74X/VHbbAnalysis/Heppy/test/crab/datasets_MCRUN2_25ns.txt ?

**Comment by arizzi** [comment]
@perrozzi was this fixed/included in current sample list?

**Comment by perrozzi** [comment]
yes the files are now included. I opened another pull request for the filelist
https://github.com/vhbb/cmssw/pull/118
I would say that I will continue to add datasets there and then can be merged just before to submit

**Comment by perrozzi** [comment]
ps just to be explicit, the datasets added for the 4b search are these
https://github.com/perrozzi/cmssw/blob/vhbb/vhbbHeppy74X/VHbbAnalysis/Heppy/test/crab/datasets_MCRUN2_25ns.txt#L174
LL174-200

**Comment by arizzi** [comment]
so we close this one

**Pull request closed without merging**
