### PR TITLE
From cmssw 7 2 2 patch2

### PR DESCRIPTION
**Pull request by veelken**
Heppy: added Pt, eta, phi of jet corresponding to tau (needed for cross-cleaning of jet collection)

### CODE REVIEW

**Comment by arizzi** [comment]
@veelken rather than changing the central Heppy object perhaps we could inherit in vhbbobj.py a vhbbTauType adding those members?
Anyhow the whole point of heppy is to do things such as cross cleaning of objects, so I'd rather sugget to write a tau-jet cross cleaning analyzer

**Comment by veelken** [comment]
@arizzi We intend to use the Ntuples for different channels in the ttH analysis. Because the jet -> tau fake-rates are on the order of a few % per jet (i.e. non-negligible in top events), the cross-cleaning wrt. taus depends on the event interpretation (i.e. on the channel that one is looking at). For this reason my preference is to do the cross-cleaning wrt. taus on analysis level.

I added the variables needed to perform the cross-cleaning wrt. taus to   
     PhysicsTools/Heppy/python/analyzers/objects/autophobj.py
because I expect the flexibility to perform the cross-cleaning on analysis level to be useful for other analyses also.

Does this explanation make sense to you or am I missing something ?

**Comment by arizzi** [comment]
Hi, probably a better solution is the store index of the jet, matching the
tau the Jets that we store in heppy.

So we can do matching in heppy but the cleaning choice only later when the
event interpetation is clear.

ciao
Andrea
Il 28/feb/2015 15:02 "Christian Veelken" <notifications@github.com> ha
scritto:

@arizzi <https://github.com/arizzi> We intend to use the Ntuples for
different channels in the ttH analysis. Because the jet -> tau fake-rates
are on the order of a few % per jet (i.e. non-negligible in top events),
the cross-cleaning wrt. taus depends on the event interpretation (i.e. on
the channel that one is looking at). For this reason my preference is to do
the cross-cleaning wrt. taus on analysis level.

I added the variables needed to perform the cross-cleaning wrt. taus to

PhysicsTools/Heppy/python/analyzers/objects/autophobj.py
because I expect the flexibility to perform the cross-cleaning on analysis
level to be useful for other analyses also.

Does this explanation make sense to you or am I missing something ?

—
Reply to this email directly or view it on GitHub
<https://github.com/vhbb/cmssw/pull/13#issuecomment-76527200>.

**Comment by veelken** [comment]
@arizzi Ok, I have updated the code to store the jet index instead of the raw jet Pt, eta, phi.
Please accept the pull request now.

**Comment by arizzi** [comment]
mhh I'm afraid this way you are storing the original index rather than the index of the jets that we actually store.
Looking at the JetAnayzer code I would do the same matching made at 
https://github.com/vhbb/cmssw/blob/vhbbHeppy722patch2/PhysicsTools/Heppy/python/analyzers/objects/JetAnalyzer.py#L156-L160
on the selected taus.

we should store in tau a .jet and in jet a .tau

then we can in our analyzer add a 
tau.jetIndex = event.cleanedJetsAll.index(tau.jet)
and/or
jet.tauIndex = event.selectedTau.index(jet.tau)

Can you give it a try to this implementation? (otherwise I'll do it tomorrow or monday)

**Pull request closed without merging**
