### PR TITLE
Merge with CMG stuff

### PR DESCRIPTION
**Pull request by arizzi**
@degrutto @azzurip we should decide if we want to include this stuff in V13 or V14

### CODE REVIEW

**Comment by degrutto** [comment]
Hi, I would say yes if you already verified that code wise we are ok,
We can then use the validation macros to see if there is any problem.
if there is any problem than we go for V14.

cheers and thanks

   Michele

**Comment by arizzi** [comment]
@jpata can you check that the CMG-big-import (i.e. this PR) doesn't mess up the storing of JEC uncerts shifts ?

**Comment by jpata** [comment]
I'm checking the big-import now. sorry for not having time earlier.

**Comment by jpata** [comment]
+1
Seems that no big effects on selection from the cmg merge. 

SL
image

DL
image

**Comment by arizzi** [comment]
adding some last minute fix
- leptons used for W kinematics (only use the selected ones!)
- set the vertex analyzer to pass all to have correct input count (

**Pull request merged**
