### PR TITLE
Vhbb heppy722patch2 tth lepton id mva

### PR DESCRIPTION
**Pull request by veelken**
- updated EGamma POG electron ID MVA
- added ttH ID+iso MVAs for electrons and muons
- added gen. Higgs decay mode

### CODE REVIEW

**Comment by arizzi** [comment]
this PR is against 722 heppy-vhbb for which we do not develop anymore:
- if you need it for sync exercises, please use directly your github
- if you want it for mainstream vhbb, please make PR against vhbbHeppy_7_4_X branch

**Comment by arizzi** [comment]
@veelken do you have a 74X version of this PR?

**Comment by veelken** [comment]
Hi Andrea,

I am traveling at the moment. It will probably take some time to migrate the PR to 74X. I will let you know once I have a tested version.

Cheers,


Christian

**Comment by arizzi** [comment]
any news?

**Comment by degrutto** [comment]
ok, my understanding is that this is not anymore needed

**Pull request closed without merging**
