### PR TITLE
factorized jec uncertainty, vhbb-side

### PR DESCRIPTION
**Pull request by jpata**
Issue: https://github.com/vhbb/cmssw/issues/566
Heppy PR: https://github.com/cbernet/cmssw/pull/78

I also needed to fix a few things related to `heppy_8_0_19` changes: `filter_func` and `outputservice`.

### CODE REVIEW

**Comment by bianchini** [comment]
@jpata @arizzi 
 - Did you figure out if the two variations are symmetric by construction? 
 - There are several other places where a loop over JEC Up/Down occurs:
https://github.com/vhbb/cmssw/blob/vhbbHeppy80X/VHbbAnalysis/Heppy/python/VHbbAnalyzer.py#L86
https://github.com/vhbb/cmssw/blob/vhbbHeppy80X/VHbbAnalysis/Heppy/python/VHbbAnalyzer.py#L284
https://github.com/vhbb/cmssw/blob/vhbbHeppy80X/VHbbAnalysis/Heppy/python/VHbbAnalyzer.py#L465
https://github.com/vhbb/cmssw/blob/vhbbHeppy80X/VHbbAnalysis/Heppy/python/vhbbobj.py#L167
https://github.com/vhbb/cmssw/blob/vhbbHeppy80X/VHbbAnalysis/Heppy/python/JetRegression.py#L70
https://github.com/vhbb/cmssw/blob/vhbbHeppy80X/VHbbAnalysis/Heppy/test/vhbb.py#L93
 we should decide whether to keep them as they are, or rather replace them with the full loop

**Comment by arizzi** [comment]
@bianchini I'd say we should centrally configure the list of variations avoiding to dup it all over the code

@jpata what's the status of the #572 ?  the PR description says you have conflicts there..
I was suggesting to create a new branch rather than merging it into current 80X

**Comment by jpata** [comment]
We need to update the GT: https://hypernews.cern.ch/HyperNews/CMS/get/jes/639.html

**Comment by bianchini** [comment]
Ok, I think we can merge this. We will track down the JEC variations everywhere else in the code importing the list from a unique place once this PR is merged

**Comment by arizzi** [comment]
should we just merge into a new branch as I was proposing so we keep the one as a V24 branch and from now we attach the release version to the branch (avoiding confusion on the base CMSSW release) ?

**Comment by jpata** [comment]
@arizzi do you mean that I should remake this PR instead against https://github.com/vhbb/cmssw/pull/572?

**Pull request merged**
