### PR TITLE
Fixed typo in softdrop parameters

### PR DESCRIPTION
**Pull request by gkasieczka**
Beta should be 1, not 0.1

### CODE REVIEW

**Comment by arizzi** [comment]
Hi, could that be the reason this version of softdrop was performing so badly on HH boosted?

**Comment by gkasieczka** [comment]
Well - this means that softdrop was run with the wrong beta parameter. And
0.1 is much close to 0 than to 1. So I'd say it's rather possible.

Cheers,
Gregor

**Comment by degrutto** [comment]
Hi,
separate question,
hopefully not creating noise,

are you still planning to look at the AK08 JEC propagation to our fat jets (so only L2L3 + residual and propagating to the mass)

cheers

   Michele

**Comment by gkasieczka** [comment]
Hi,

yeah - I started working on this now.

Cheers,
Gregor

**Comment by degrutto** [comment]
Hi @gkasieczka 

is this contained already in #250 ?
If so we can close this PR

**Comment by gkasieczka** [comment]
Hi Michele,

thanks for the reminder. No it is not, but I will add it to the new PR
(it's trivial). So this can be closed

Cheers,
Gregor

**Pull request closed without merging**
