### PR TITLE
Dev flexible preprocessor

### PR DESCRIPTION
**Pull request by gkasieczka**
Turn on/off options in preprocessor and vhbb_combined, depending if we run on data or not. Should be used with #148

### CODE REVIEW

**Comment by gkasieczka** [comment]
So I went with the second approach - making the preprocessor more flexible. The cmssw_combined code is not mostly one function called initialize that returns the process object and that can receive options from cmsswPreprocessor.py. This should be general enough - ie the python part can pass along any dictionary of options to the cmssw config script. 

If a "classic" config file (without an initialise function) is provided, everything works as before.

**Comment by arizzi** [comment]
ah but I was more thinking something like
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideAboutPythonConfigFile#Passing_Command_Line_Arguments_T

where we just use standard cmsRun options facility

**Comment by gkasieczka** [comment]
I considered that. This would mean - if we want arbitrary options - to "unwrap" them and pass via the shell only to re-assemble the options list. I went with the other approach because I thought having a function return the process is a good trade-off for simplifying the rest of the transaction.

**Comment by arizzi** [comment]
can you make also a PR containing only the Heppy change to @cbernet repository?

**Comment by gkasieczka** [comment]
Thank you!
Done as: https://github.com/cbernet/cmssw/pull/55

**Pull request merged**
