### PR TITLE
location of XML files for EGamma POG electron ID MVA 

### PR DESCRIPTION
**Pull request by veelken**
updated location of XML files for Phys14 training to RecoEgamma/ElectronIdentification ,
as recommeded by EGamma POG converner on Hypernews https://hypernews.cern.ch/HyperNews/CMS/get/egamma-elecid/111/1/1/1/1/1/1/1.html

### CODE REVIEW

**Comment by arizzi** [comment]
@cbernet @gpetruc this may need to go in central Heppy too (will make a PR with all out Heppy76X things net week)

**Comment by gpetruc** [comment]
I think we should drop entirely the Phys14 electron ID from 76X.

**Comment by veelken** [comment]
Hi Giovanni,
my understanding is that the Phys14 electron ID MVA is used as input variable for the ttH prompt lepton MVA in CMSSW 7_6_x. I agree that all older XML files can be dropped.

**Comment by gpetruc** [comment]
Hi Christian,

Not any longer, we're now using the Spring15 MVA electron ID. See
https://indico.cern.ch/event/476024/?filterActive=1&showDate=all&showSession=16#2016-01-11

Ciao,

   Giovanni

On Thu, Jan 21, 2016 at 1:41 PM, Christian Veelken <notifications@github.com

**Comment by veelken** [comment]
Hi Giovanni,

the wiki https://twiki.cern.ch/twiki/bin/view/CMS/TTH-Multileptons#Object_ID still refers to the Phys14 version. Can you point me to the new version please ?

Thank you,


Christian

**Pull request merged**
