### PR TITLE
ttH-Htt 29.06.16

### PR DESCRIPTION
**Pull request by ktht**
- relax lepton pT cuts
  - muons 10 -> 4.5; electrons 10 -> 6.5
  - tested: the number of gen level b-jets vetoed by leptons of lower pT increased by ~1%
- set electron abs eta cut to 2.5 (default 2.4)
- allow to use different rho for mini-isolation
- include mini-isolation in the isolation cuts as well

edit/update:
- use jet pT value after JEC in jetPtRatio (lepton pT / nearest jet pT)
- move a few lines to the end of process() in VhbbAnalyzer so that the values for Ntuple branches are always calculated

### CODE REVIEW

**Comment by bianchini** [comment]
Ciao, you should factorize the commits into a Heppy one and one that goes to vhbb only. We should pass heppy commits to the Heppy administrators, and if they approve it we get it into central Heppy.

**Comment by ktht** [comment]
Hi again, I split the old commit into two and added another two commits. Nothing more to commit on my part.

**Comment by bianchini** [comment]
Hi Karl, I don't understand the logic of https://github.com/vhbb/cmssw/pull/472/commits/5bc4200ca175725aa9e3667a93404723f979ad70. If you don't return for uninteresting events, you will be always be calling sequences for nothing, and that may also crash if they rely on two jets

**Comment by ktht** [comment]
The reason we moved these 4 lines there was that the analysis chain never reached to TTHtoTauTauAnalayzer (probably because some variables weren't computed and thus the subsequent analysis failed). This was a problem in synchronization 10 mo ago (missing some events), so we came up with this quick fix. Still, we haven't observed any issues related to this change.

**Comment by bianchini** [comment]
Uhm... I am not sure.

First thing is to make sure that all these sequences:
self.doHiggsHighCSV(event)
self.doHiggsHighPt(event)
self.doHiggsAddJetsdR08(event)
self.searchISRforVH(event)
self.doVHRegression(event)
self.doVBFblikelihood(event)
self.doVBF(event)
self.doSoftActivityVH(event)
do not crash if you don't pass the basic vhbb selection.
Second, as I can see it, the way you propose will just make all these sequences be run for all events, but whether an event will be  kept or not is decided by

if not  ( len(event.jetsForHiggs) >= 2  or (len(event.cleanJets) == 1 and event.cleanJets[0].pt() > ssThreshold ) ) :
        return self.cfg_ana.passall
        if event.Vtype < 0 and not ( sum(x.pt() > 30 for x in event.jetsForHiggs) >= 4 or sum(x.pt() for x in event.jetsForHiggs[:4]) > 160 ):
return self.cfg_ana.passall

and you have not touched it, so how can this affect your synchronisation?

**Comment by ktht** [comment]
About your second point: yes, it's true that shouldn't affect synchronization, _unless_ `passall` is set to `True` in [vhbb.py](https://github.com/vhbb/cmssw/blob/vhbbHeppy80X/VHbbAnalysis/Heppy/test/vhbb.py#L312). In the original code, if we set it to `True` (i.e. also include uninteresting events, which we did in synchronization iirc), the events are passed to the next Analyzer. So TTHtoTauTauAnalayzer failed because it was dealing with undefined or otherwise unexpected values.

About your first point: we've run the modified VHbbAnalyzer.py on various samples in the past 10 months and have never experienced a crash. Although, I admit that it's not a quality benchmark to follow.

**Comment by bianchini** [comment]
Ok. passAll=true is something that we want to avoid given that the size of the samples would increase beyond what we can afford.
Can you formulate the extra selection you need for the sync like in
https://github.com/ktht/cmssw/blob/5bc4200ca175725aa9e3667a93404723f979ad70/VHbbAnalysis/Heppy/python/VHbbAnalyzer.py#L548?
How much would the event yield change?

**Comment by ktht** [comment]
Closing this PR and create a new one based on this in a moment.

**Pull request closed without merging**
