### PR TITLE
add function to fix trigger path in reHLT

### PR DESCRIPTION
**Pull request by jpata**
https://github.com/vhbb/cmssw/issues/486

### CODE REVIEW

**Comment by perrozzi** [comment]
what about this?
@cvernier do you have any other version of this that you used during the V23 submission?

**Comment by jpata** [comment]
I currently rely on this in my code. It works seamlessly, based on the actual received filename. However, one needs to change `heppy_crab_script.py` as well, I don't use that script for submission.

**Comment by perrozzi** [comment]
@cvernier may I kindly ask you to test this PR with the crab wrapper we use for vh?

**Comment by cvernier** [comment]
It works!

**Comment by perrozzi** [comment]
https://github.com/vhbb/cmssw/pull/522

**Pull request merged**
